name: push jinwei/imagehome:rl

on:
  push:
    branches:
    - devel
    paths:
    - dockerfiles/torch1.8.1_cuda11.1/*
    - .github/workflows/push_torch1.8.1_cuda11.1.yml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: jinwei/imagehome
        tags: rl-torch1.8.1-cuda11.1-devel
        path: dockerfiles/torch1.8.1_cuda11.1
